apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simple Release
on:
  workflow_dispatch:
jobs:
  pre-prod:
    steps:
      - name: Create manifest
        # This really should be in a separate job, but no file sharing between jobs
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          cat << EOF | tee manifest.yaml
          [{"component_id":"40e01279-51b0-42a4-8464-26a9c13f0287","branch_name":"main","workflow_file_name":"deploy.yaml","inputs":"{\"environment\":\"pre-prod\",\"name\":\"MyAppFE\",\"version\":\"3.0.0-0.0.2\"}"},{"component_id":"9bd5b564-6f71-49f9-b4fb-047bbab802ed","branch_name":"main","workflow_file_name":"deploy.yaml","inputs":"{\"environment\":\"pre-prod\",\"name\":\"MyAppBE\",\"version\":\"2.0.0-0.0.3\"}"},{"component_id":"9bd5b564-6f71-49f9-b4fb-047bbab802ed","branch_name":"main","workflow_file_name":"deploy.yaml","inputs":"{\"environment\":\"$$ENV$$\",\"name\":\"MyAppFE\",\"version\":\"1.0.0-0.0.1\"}"}]
          EOF
      - name: deploy
        uses: cloudbees-io/workflows-dispatch
        with:
          workflows-dispatch-file: manifest.yaml
          token: ${{ secrets.PAT}}
